version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  svm_service:
    build:
      context: ./backend/svm
    ports:
      - "5000:5000"

  vgg19_service:
    build:
      context: ./backend/vgg19
    ports:
      - "5001:5001"
